In [1]:
import pandas as pd

data = {
    'study_hours': [1, 2, 3, 4, 5, 6, 7, 8],
    'attendance': [50, 55, 60, 65, 70, 75, 80, 85],
    'pass':        [0, 0, 0, 0, 1, 1, 1, 1]
}

df = pd.DataFrame(data)

df

   study_hours  attendance  pass
0            1          50     0
1            2          55     0
2            3          60     0
3            4          65     0
4            5          70     1
5            6          75     1
6            7          80     1
7            8          85     1

In [2]:
X = df[['study_hours', 'attendance']]
y = df['pass']

In [3]:
from sklearn.linear_model import Perceptron

In [4]:
p = Perceptron()

In [5]:
p.fit(X, y)

Perceptron()

In [6]:
p.coef_

array([[67., 65.]])

In [7]:
p.intercept_

array([-6.])

In [8]:
new_students = [
    [2, 55],
    [6, 75],
    [8, 90]
]

In [10]:
print("New Predictions:", p.predict(new_students))

New Predictions: [1 1 1]

c:\Users\g11111\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but Perceptron was fitted with feature names
  warnings.warn(

In [9]:
p.predict(new_students)

c:\Users\g11111\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but Perceptron was fitted with feature names
  warnings.warn(

array([1, 1, 1])

In [11]:
new_students = pd.DataFrame({
    'study_hours': [2, 6, 8],
    'attendance': [55, 75, 90]
})

In [12]:
new_students

   study_hours  attendance
0            2          55
1            6          75
2            8          90

In [14]:
from sklearn.preprocessing import StandardScaler

In [19]:
scaler = StandardScaler()

In [21]:
X = df[['study_hours', 'attendance']]
y = df['pass']

X_scaled = scaler.fit_transform(X)

In [22]:
new_students_scaled = scaler.transform(new_students)

p.predict(new_students_scaled)

c:\Users\g11111\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but Perceptron was fitted with feature names
  warnings.warn(

array([0, 1, 1])

In [23]:
from sklearn.linear_model import Perceptron

p = Perceptron()

p.fit(X_scaled, y)

Perceptron()

In [24]:
new_students = pd.DataFrame({
    'study_hours': [2, 6, 8],
    'attendance': [55, 75, 90]
})

In [25]:
new_students_scaled = scaler.transform(new_students)

In [27]:
new_students_scaled = scaler.transform(new_students)

In [29]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

In [33]:
new_students_scaled = scaler.transform(new_students)

In [37]:
X_scaled = scaler.fit_transform(X)

In [47]:
new_students_scaled = scaler.transform(new_students)

In [44]:
new_students_scaled = scaler.transform(new_students)

In [45]:
new_students

   study_hours  attendance
0            2          55
1            6          75
2            8          90

In [42]:
scaler.fit(X)

StandardScaler()